apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
  namespace: devops
data:
  nginx.conf: |
    events {
      worker_connections  1024;
    }
    http {
      server {
        listen 8080;
        listen [::]:8080;
        server_name localhost;

        location / {
        proxy_pass http://localhost:80/;
        }
      
        location /homepage {
        proxy_pass http://localhost:80/homepage;
        }

        location /another-route {
        proxy_pass http://localhost:80/another-route;
        }
      
        error_page 500 502 503 504 /50x.html;
        location = /50x.html {
        root /usr/share/nginx/html;
        }
      }
    }
