apiVersion: v1
kind: Service
metadata:
  name: devops-service
  namespace: devops-labs
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30128
  selector:
    app: devops
